name: FlyTicket Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build Step
      run: echo "Building FlyTicket Project..."

    - name: Build Report
      run: echo "Build Status: SUCCESS"

    - name: Deploy Step
      run: echo "Deploying FlyTicket Website..."

    - name: Deploy Report
      run: echo "Deployment Status: SUCCESS"
